package net.megal.uselessadditions.item;

import net.fabricmc.fabric.api.item.v1.FabricItemSettings;
import net.fabricmc.fabric.api.itemgroup.v1.ItemGroupEvents;
import net.megal.uselessadditions.UAdd;
import net.megal.uselessadditions.entity.UEntities;
import net.megal.uselessadditions.item.base.*;
import net.megal.uselessadditions.item.bundles.*;
import net.minecraft.entity.EntityType;
import net.minecraft.entity.mob.MobEntity;
import net.minecraft.item.*;
import net.minecraft.registry.Registry;
import net.minecraft.registry.Registries;
import net.minecraft.text.Text;
import net.minecraft.util.Formatting;
import net.minecraft.util.Identifier;
import net.minecraft.util.Rarity;

import java.util.List;

import static net.megal.uselessadditions.block.UBlocks.*;

public class UItems {
    //Vanilla Spawn Eggs
    public static final SpawnEggItem V_FRIGID_ZOMBIE_SPAWN_EGG = registerItem(new Identifier(UAdd.MOD_ID, "vanilla_frigid_zombie_spawn_egg"), new SpawnEggItem(UEntities.FRIGID_ZOMBIE, 0x214263, 0x508084, new FabricItemSettings()));
    //Mob Ore Shards
    public static final Item ALLAY_SHARD = registerItem(new Identifier(UAdd.MOD_ID, "allay_shard"), createItem());
    public static final Item AXOLOTL_SHARD = registerItem(new Identifier(UAdd.MOD_ID, "axolotl_shard"), createItem());
    public static final Item BAT_SHARD = registerItem(new Identifier(UAdd.MOD_ID, "bat_shard"), createItem());
    public static final Item BEE_SHARD = registerItem(new Identifier(UAdd.MOD_ID, "bee_shard"), createItem());
    public static final Item BLAZE_SHARD = registerItem(new Identifier(UAdd.MOD_ID, "blaze_shard"), createItem());
    public static final Item CAT_SHARD = registerItem(new Identifier(UAdd.MOD_ID, "cat_shard"), createItem());
    public static final Item CAVE_SPIDER_SHARD = registerItem(new Identifier(UAdd.MOD_ID, "cave_spider_shard"), createItem());
    public static final Item CHICKEN_SHARD = registerItem(new Identifier(UAdd.MOD_ID, "chicken_shard"), createItem());
    public static final Item COD_SHARD = registerItem(new Identifier(UAdd.MOD_ID, "cod_shard"), createItem());
    public static final Item COW_SHARD = registerItem(new Identifier(UAdd.MOD_ID, "cow_shard"), createItem());
    public static final Item CREEPER_SHARD = registerItem(new Identifier(UAdd.MOD_ID, "creeper_shard"), createItem());
    public static final Item DOLPHIN_SHARD = registerItem(new Identifier(UAdd.MOD_ID, "dolphin_shard"), createItem());
    public static final Item DONKEY_SHARD = registerItem(new Identifier(UAdd.MOD_ID, "donkey_shard"), createItem());
    public static final Item ENDERMAN_SHARD = registerItem(new Identifier(UAdd.MOD_ID, "enderman_shard"), createItem());
    public static final Item ENDERMITE_SHARD = registerItem(new Identifier(UAdd.MOD_ID, "endermite_shard"), createItem());
    public static final Item EVOKER_SHARD = registerItem(new Identifier(UAdd.MOD_ID, "evoker_shard"), createItem());
    public static final Item FOX_SHARD = registerItem(new Identifier(UAdd.MOD_ID, "fox_shard"), createItem());
    public static final Item FROG_SHARD = registerItem(new Identifier(UAdd.MOD_ID, "frog_shard"), createItem());
    public static final Item GHAST_SHARD = registerItem(new Identifier(UAdd.MOD_ID, "ghast_shard"), createItem());
    public static final Item GLOW_SQUID_SHARD = registerItem(new Identifier(UAdd.MOD_ID, "glow_squid_shard"), createItem());
    public static final Item GOAT_SHARD = registerItem(new Identifier(UAdd.MOD_ID, "goat_shard"), createItem());
    public static final Item GUARDIAN_SHARD = registerItem(new Identifier(UAdd.MOD_ID, "guardian_shard"), createItem());
    public static final Item HOGLIN_SHARD = registerItem(new Identifier(UAdd.MOD_ID, "hoglin_shard"), createItem());
    public static final Item HORSE_SHARD = registerItem(new Identifier(UAdd.MOD_ID, "horse_shard"), createItem());
    public static final Item IRON_GOLEM_SHARD = registerItem(new Identifier(UAdd.MOD_ID, "iron_golem_shard"), createItem());
    public static final Item LLAMA_SHARD = registerItem(new Identifier(UAdd.MOD_ID, "llama_shard"), createItem());
    public static final Item MAGMA_CUBE_SHARD = registerItem(new Identifier(UAdd.MOD_ID, "magma_cube_shard"), createItem());
    public static final Item OCELOT_SHARD = registerItem(new Identifier(UAdd.MOD_ID, "ocelot_shard"), createItem());
    public static final Item PANDA_SHARD = registerItem(new Identifier(UAdd.MOD_ID, "panda_shard"), createItem());
    public static final Item PARROT_SHARD = registerItem(new Identifier(UAdd.MOD_ID, "parrot_shard"), createItem());
    public static final Item PHANTOM_SHARD = registerItem(new Identifier(UAdd.MOD_ID, "phantom_shard"), createItem());
    public static final Item PIG_SHARD = registerItem(new Identifier(UAdd.MOD_ID, "pig_shard"), createItem());
    public static final Item PIGLIN_SHARD = registerItem(new Identifier(UAdd.MOD_ID, "piglin_shard"), createItem());
    public static final Item PILLAGER_SHARD = registerItem(new Identifier(UAdd.MOD_ID, "pillager_shard"), createItem());
    public static final Item POLAR_BEAR_SHARD = registerItem(new Identifier(UAdd.MOD_ID, "polar_bear_shard"), createItem());
    public static final Item PUFFERFISH_SHARD = registerItem(new Identifier(UAdd.MOD_ID, "pufferfish_shard"), createItem());
    public static final Item RABBIT_SHARD = registerItem(new Identifier(UAdd.MOD_ID, "rabbit_shard"), createItem());
    public static final Item RAVAGER_SHARD = registerItem(new Identifier(UAdd.MOD_ID, "ravager_shard"), createItem());
    public static final Item SALMON_SHARD = registerItem(new Identifier(UAdd.MOD_ID, "salmon_shard"), createItem());
    public static final Item SHEEP_SHARD = registerItem(new Identifier(UAdd.MOD_ID, "sheep_shard"), createItem());
    public static final Item SHULKER_SHARD = registerItem(new Identifier(UAdd.MOD_ID, "shulker_shard"), createItem());
    public static final Item SILVERFISH_SHARD = registerItem(new Identifier(UAdd.MOD_ID, "silverfish_shard"), createItem());
    public static final Item SKELETON_SHARD = registerItem(new Identifier(UAdd.MOD_ID, "skeleton_shard"), createItem());
    public static final Item SLIME_SHARD = registerItem(new Identifier(UAdd.MOD_ID, "slime_shard"), createItem());
    public static final Item SNOW_GOLEM_SHARD = registerItem(new Identifier(UAdd.MOD_ID, "snow_golem_shard"), createItem());
    public static final Item SPIDER_SHARD = registerItem(new Identifier(UAdd.MOD_ID, "spider_shard"), createItem());
    public static final Item SQUID_SHARD = registerItem(new Identifier(UAdd.MOD_ID, "squid_shard"), createItem());
    public static final Item STRIDER_SHARD = registerItem(new Identifier(UAdd.MOD_ID, "strider_shard"), createItem());
    public static final Item TROPICAL_FISH_SHARD = registerItem(new Identifier(UAdd.MOD_ID, "tropical_fish_shard"), createItem());
    public static final Item TURTLE_SHARD = registerItem(new Identifier(UAdd.MOD_ID, "turtle_shard"), createItem());
    public static final Item VEX_SHARD = registerItem(new Identifier(UAdd.MOD_ID, "vex_shard"), createItem());
    public static final Item VILLAGER_SHARD = registerItem(new Identifier(UAdd.MOD_ID, "villager_shard"), createItem());
    public static final Item VINDICATOR_SHARD = registerItem(new Identifier(UAdd.MOD_ID, "vindicator_shard"), createItem());
    public static final Item WARDEN_SHARD = registerItem(new Identifier(UAdd.MOD_ID, "warden_shard"), createItem());
    public static final Item WITCH_SHARD = registerItem(new Identifier(UAdd.MOD_ID, "witch_shard"), createItem());
    public static final Item WITHER_SKELETON_SHARD = registerItem(new Identifier(UAdd.MOD_ID, "wither_skeleton_shard"), createItem());
    public static final Item WOLF_SHARD = registerItem(new Identifier(UAdd.MOD_ID, "wolf_shard"), createItem());
    public static final Item ZOMBIE_SHARD = registerItem(new Identifier(UAdd.MOD_ID, "zombie_shard"), createItem());
    public static final Item SMALL_ALLAY_SHARD = registerItem(new Identifier(UAdd.MOD_ID, "small_allay_shard"), createItem());
    public static final Item SMALL_AXOLOTL_SHARD = registerItem(new Identifier(UAdd.MOD_ID, "small_axolotl_shard"), createItem());
    public static final Item SMALL_BAT_SHARD = registerItem(new Identifier(UAdd.MOD_ID, "small_bat_shard"), createItem());
    public static final Item SMALL_BEE_SHARD = registerItem(new Identifier(UAdd.MOD_ID, "small_bee_shard"), createItem());
    public static final Item SMALL_BLAZE_SHARD = registerItem(new Identifier(UAdd.MOD_ID, "small_blaze_shard"), createItem());
    public static final Item SMALL_CAT_SHARD = registerItem(new Identifier(UAdd.MOD_ID, "small_cat_shard"), createItem());
    public static final Item SMALL_CAVE_SPIDER_SHARD = registerItem(new Identifier(UAdd.MOD_ID, "small_cave_spider_shard"), createItem());
    public static final Item SMALL_CHICKEN_SHARD = registerItem(new Identifier(UAdd.MOD_ID, "small_chicken_shard"), createItem());
    public static final Item SMALL_COD_SHARD = registerItem(new Identifier(UAdd.MOD_ID, "small_cod_shard"), createItem());
    public static final Item SMALL_COW_SHARD = registerItem(new Identifier(UAdd.MOD_ID, "small_cow_shard"), createItem());
    public static final Item SMALL_CREEPER_SHARD = registerItem(new Identifier(UAdd.MOD_ID, "small_creeper_shard"), createItem());
    public static final Item SMALL_DOLPHIN_SHARD = registerItem(new Identifier(UAdd.MOD_ID, "small_dolphin_shard"), createItem());
    public static final Item SMALL_DONKEY_SHARD = registerItem(new Identifier(UAdd.MOD_ID, "small_donkey_shard"), createItem());
    public static final Item SMALL_ENDERMAN_SHARD = registerItem(new Identifier(UAdd.MOD_ID, "small_enderman_shard"), createItem());
    public static final Item SMALL_ENDERMITE_SHARD = registerItem(new Identifier(UAdd.MOD_ID, "small_endermite_shard"), createItem());
    public static final Item SMALL_EVOKER_SHARD = registerItem(new Identifier(UAdd.MOD_ID, "small_evoker_shard"), createItem());
    public static final Item SMALL_FOX_SHARD = registerItem(new Identifier(UAdd.MOD_ID, "small_fox_shard"), createItem());
    public static final Item SMALL_FROG_SHARD = registerItem(new Identifier(UAdd.MOD_ID, "small_frog_shard"), createItem());
    public static final Item SMALL_GHAST_SHARD = registerItem(new Identifier(UAdd.MOD_ID, "small_ghast_shard"), createItem());
    public static final Item SMALL_GLOW_SQUID_SHARD = registerItem(new Identifier(UAdd.MOD_ID, "small_glow_squid_shard"), createItem());
    public static final Item SMALL_GOAT_SHARD = registerItem(new Identifier(UAdd.MOD_ID, "small_goat_shard"), createItem());
    public static final Item SMALL_GUARDIAN_SHARD = registerItem(new Identifier(UAdd.MOD_ID, "small_guardian_shard"), createItem());
    public static final Item SMALL_HOGLIN_SHARD = registerItem(new Identifier(UAdd.MOD_ID, "small_hoglin_shard"), createItem());
    public static final Item SMALL_HORSE_SHARD = registerItem(new Identifier(UAdd.MOD_ID, "small_horse_shard"), createItem());
    public static final Item SMALL_IRON_GOLEM_SHARD = registerItem(new Identifier(UAdd.MOD_ID, "small_iron_golem_shard"), createItem());
    public static final Item SMALL_LLAMA_SHARD = registerItem(new Identifier(UAdd.MOD_ID, "small_llama_shard"), createItem());
    public static final Item SMALL_MAGMA_CUBE_SHARD = registerItem(new Identifier(UAdd.MOD_ID, "small_magma_cube_shard"), createItem());
    public static final Item SMALL_OCELOT_SHARD = registerItem(new Identifier(UAdd.MOD_ID, "small_ocelot_shard"), createItem());
    public static final Item SMALL_PANDA_SHARD = registerItem(new Identifier(UAdd.MOD_ID, "small_panda_shard"), createItem());
    public static final Item SMALL_PARROT_SHARD = registerItem(new Identifier(UAdd.MOD_ID, "small_parrot_shard"), createItem());
    public static final Item SMALL_PHANTOM_SHARD = registerItem(new Identifier(UAdd.MOD_ID, "small_phantom_shard"), createItem());
    public static final Item SMALL_PIG_SHARD = registerItem(new Identifier(UAdd.MOD_ID, "small_pig_shard"), createItem());
    public static final Item SMALL_PIGLIN_SHARD = registerItem(new Identifier(UAdd.MOD_ID, "small_piglin_shard"), createItem());
    public static final Item SMALL_PILLAGER_SHARD = registerItem(new Identifier(UAdd.MOD_ID, "small_pillager_shard"), createItem());
    public static final Item SMALL_POLAR_BEAR_SHARD = registerItem(new Identifier(UAdd.MOD_ID, "small_polar_bear_shard"), createItem());
    public static final Item SMALL_PUFFERFISH_SHARD = registerItem(new Identifier(UAdd.MOD_ID, "small_pufferfish_shard"), createItem());
    public static final Item SMALL_RABBIT_SHARD = registerItem(new Identifier(UAdd.MOD_ID, "small_rabbit_shard"), createItem());
    public static final Item SMALL_RAVAGER_SHARD = registerItem(new Identifier(UAdd.MOD_ID, "small_ravager_shard"), createItem());
    public static final Item SMALL_SALMON_SHARD = registerItem(new Identifier(UAdd.MOD_ID, "small_salmon_shard"), createItem());
    public static final Item SMALL_SHEEP_SHARD = registerItem(new Identifier(UAdd.MOD_ID, "small_sheep_shard"), createItem());
    public static final Item SMALL_SHULKER_SHARD = registerItem(new Identifier(UAdd.MOD_ID, "small_shulker_shard"), createItem());
    public static final Item SMALL_SILVERFISH_SHARD = registerItem(new Identifier(UAdd.MOD_ID, "small_silverfish_shard"), createItem());
    public static final Item SMALL_SKELETON_SHARD = registerItem(new Identifier(UAdd.MOD_ID, "small_skeleton_shard"), createItem());
    public static final Item SMALL_SLIME_SHARD = registerItem(new Identifier(UAdd.MOD_ID, "small_slime_shard"), createItem());
    public static final Item SMALL_SNOW_GOLEM_SHARD = registerItem(new Identifier(UAdd.MOD_ID, "small_snow_golem_shard"), createItem());
    public static final Item SMALL_SPIDER_SHARD = registerItem(new Identifier(UAdd.MOD_ID, "small_spider_shard"), createItem());
    public static final Item SMALL_SQUID_SHARD = registerItem(new Identifier(UAdd.MOD_ID, "small_squid_shard"), createItem());
    public static final Item SMALL_STRIDER_SHARD = registerItem(new Identifier(UAdd.MOD_ID, "small_strider_shard"), createItem());
    public static final Item SMALL_TROPICAL_FISH_SHARD = registerItem(new Identifier(UAdd.MOD_ID, "small_tropical_fish_shard"), createItem());
    public static final Item SMALL_TURTLE_SHARD = registerItem(new Identifier(UAdd.MOD_ID, "small_turtle_shard"), createItem());
    public static final Item SMALL_VEX_SHARD = registerItem(new Identifier(UAdd.MOD_ID, "small_vex_shard"), createItem());
    public static final Item SMALL_VILLAGER_SHARD = registerItem(new Identifier(UAdd.MOD_ID, "small_villager_shard"), createItem());
    public static final Item SMALL_VINDICATOR_SHARD = registerItem(new Identifier(UAdd.MOD_ID, "small_vindicator_shard"), createItem());
    public static final Item SMALL_WARDEN_SHARD = registerItem(new Identifier(UAdd.MOD_ID, "small_warden_shard"), createItem());
    public static final Item SMALL_WITCH_SHARD = registerItem(new Identifier(UAdd.MOD_ID, "small_witch_shard"), createItem());
    public static final Item SMALL_WITHER_SKELETON_SHARD = registerItem(new Identifier(UAdd.MOD_ID, "small_wither_skeleton_shard"), createItem());
    public static final Item SMALL_WOLF_SHARD = registerItem(new Identifier(UAdd.MOD_ID, "small_wolf_shard"), createItem());
    public static final Item SMALL_ZOMBIE_SHARD = registerItem(new Identifier(UAdd.MOD_ID, "small_zombie_shard"), createItem());
    //Spawn Eggs
    public static final SpawnEgg ALLAY_SPAWN_EGG = registerItem(new Identifier(UAdd.MOD_ID, "allay_spawn_egg"), createSpawnEgg(EntityType.ALLAY));
    public static final SpawnEgg AXOLOTL_SPAWN_EGG = registerItem(new Identifier(UAdd.MOD_ID, "axolotl_spawn_egg"), createSpawnEgg(EntityType.AXOLOTL));
    public static final SpawnEgg BAT_SPAWN_EGG = registerItem(new Identifier(UAdd.MOD_ID, "bat_spawn_egg"), createSpawnEgg(EntityType.BAT));
    public static final SpawnEgg BEE_SPAWN_EGG = registerItem(new Identifier(UAdd.MOD_ID, "bee_spawn_egg"), createSpawnEgg(EntityType.BEE));
    public static final SpawnEgg BLAZE_SPAWN_EGG = registerItem(new Identifier(UAdd.MOD_ID, "blaze_spawn_egg"), createSpawnEgg(EntityType.BLAZE));
    public static final SpawnEgg CAT_SPAWN_EGG = registerItem(new Identifier(UAdd.MOD_ID, "cat_spawn_egg"), createSpawnEgg(EntityType.CAT));
    public static final SpawnEgg CAVE_SPIDER_SPAWN_EGG = registerItem(new Identifier(UAdd.MOD_ID, "cave_spider_spawn_egg"), createSpawnEgg(EntityType.CAVE_SPIDER));
    public static final SpawnEgg CHICKEN_SPAWN_EGG = registerItem(new Identifier(UAdd.MOD_ID, "chicken_spawn_egg"), createSpawnEgg(EntityType.CHICKEN));
    public static final SpawnEgg COD_SPAWN_EGG = registerItem(new Identifier(UAdd.MOD_ID, "cod_spawn_egg"), createSpawnEgg(EntityType.COD));
    public static final SpawnEgg COW_SPAWN_EGG = registerItem(new Identifier(UAdd.MOD_ID, "cow_spawn_egg"), createSpawnEgg(EntityType.COW));
    public static final SpawnEgg CREEPER_SPAWN_EGG = registerItem(new Identifier(UAdd.MOD_ID, "creeper_spawn_egg"), createSpawnEgg(EntityType.CREEPER));
    public static final SpawnEgg DROWNED_SPAWN_EGG = registerItem(new Identifier(UAdd.MOD_ID, "drowned_spawn_egg"), createSpawnEgg(EntityType.DROWNED));
    public static final SpawnEgg DOLPHIN_SPAWN_EGG = registerItem(new Identifier(UAdd.MOD_ID, "dolphin_spawn_egg"), createSpawnEgg(EntityType.DOLPHIN));
    public static final SpawnEgg DONKEY_SPAWN_EGG = registerItem(new Identifier(UAdd.MOD_ID, "donkey_spawn_egg"), createSpawnEgg(EntityType.DONKEY));
    public static final SpawnEgg ELDER_GUARDIAN_SPAWN_EGG = registerItem(new Identifier(UAdd.MOD_ID, "elder_guardian_spawn_egg"), createSpawnEgg(EntityType.ELDER_GUARDIAN));
    public static final SpawnEgg ENDERMAN_SPAWN_EGG = registerItem(new Identifier(UAdd.MOD_ID, "enderman_spawn_egg"), createSpawnEgg(EntityType.ENDERMAN));
    public static final SpawnEgg ENDERMITE_SPAWN_EGG = registerItem(new Identifier(UAdd.MOD_ID, "endermite_spawn_egg"), createSpawnEgg(EntityType.ENDERMITE));
    public static final SpawnEgg EVOKER_SPAWN_EGG = registerItem(new Identifier(UAdd.MOD_ID, "evoker_spawn_egg"), createSpawnEgg(EntityType.EVOKER));
    public static final SpawnEgg FOX_SPAWN_EGG = registerItem(new Identifier(UAdd.MOD_ID, "fox_spawn_egg"), createSpawnEgg(EntityType.FOX));
    public static final SpawnEgg FRIGID_ZOMBIE_SPAWN_EGG = registerItem(new Identifier(UAdd.MOD_ID, "frigid_zombie_spawn_egg"), createSpawnEgg(UEntities.FRIGID_ZOMBIE));
    public static final SpawnEgg FROG_SPAWN_EGG = registerItem(new Identifier(UAdd.MOD_ID, "frog_spawn_egg"), createSpawnEgg(EntityType.FROG));
    public static final SpawnEgg GHAST_SPAWN_EGG = registerItem(new Identifier(UAdd.MOD_ID, "ghast_spawn_egg"), createSpawnEgg(EntityType.GHAST));
    public static final SpawnEgg GLOW_SQUID_SPAWN_EGG = registerItem(new Identifier(UAdd.MOD_ID, "glow_squid_spawn_egg"), createSpawnEgg(EntityType.GLOW_SQUID));
    public static final SpawnEgg GOAT_SPAWN_EGG = registerItem(new Identifier(UAdd.MOD_ID, "goat_spawn_egg"), createSpawnEgg(EntityType.GOAT));
    public static final SpawnEgg GUARDIAN_SPAWN_EGG = registerItem(new Identifier(UAdd.MOD_ID, "guardian_spawn_egg"), createSpawnEgg(EntityType.GUARDIAN));
    public static final SpawnEgg HOGLIN_SPAWN_EGG = registerItem(new Identifier(UAdd.MOD_ID, "hoglin_spawn_egg"), createSpawnEgg(EntityType.HOGLIN));
    public static final SpawnEgg HORSE_SPAWN_EGG = registerItem(new Identifier(UAdd.MOD_ID, "horse_spawn_egg"), createSpawnEgg(EntityType.HORSE));
    public static final SpawnEgg HUSK_SPAWN_EGG = registerItem(new Identifier(UAdd.MOD_ID, "husk_spawn_egg"), createSpawnEgg(EntityType.HUSK));
    public static final SpawnEgg IRON_GOLEM_SPAWN_EGG = registerItem(new Identifier(UAdd.MOD_ID, "iron_golem_spawn_egg"), createSpawnEgg(EntityType.IRON_GOLEM));
    public static final SpawnEgg LLAMA_SPAWN_EGG = registerItem(new Identifier(UAdd.MOD_ID, "llama_spawn_egg"), createSpawnEgg(EntityType.LLAMA));
    public static final SpawnEgg MAGMA_CUBE_SPAWN_EGG = registerItem(new Identifier(UAdd.MOD_ID, "magma_cube_spawn_egg"), createSpawnEgg(EntityType.MAGMA_CUBE));
    public static final SpawnEgg OCELOT_SPAWN_EGG = registerItem(new Identifier(UAdd.MOD_ID, "ocelot_spawn_egg"), createSpawnEgg(EntityType.OCELOT));
    public static final SpawnEgg PANDA_SPAWN_EGG = registerItem(new Identifier(UAdd.MOD_ID, "panda_spawn_egg"), createSpawnEgg(EntityType.PANDA));
    public static final SpawnEgg PARROT_SPAWN_EGG = registerItem(new Identifier(UAdd.MOD_ID, "parrot_spawn_egg"), createSpawnEgg(EntityType.PARROT));
    public static final SpawnEgg PHANTOM_SPAWN_EGG = registerItem(new Identifier(UAdd.MOD_ID, "phantom_spawn_egg"), createSpawnEgg(EntityType.PHANTOM));
    public static final SpawnEgg PIG_SPAWN_EGG = registerItem(new Identifier(UAdd.MOD_ID, "pig_spawn_egg"), createSpawnEgg(EntityType.PIG));
    public static final SpawnEgg PIGLIN_SPAWN_EGG = registerItem(new Identifier(UAdd.MOD_ID, "piglin_spawn_egg"), createSpawnEgg(EntityType.PIGLIN));
    public static final SpawnEgg PIGLIN_BRUTE_SPAWN_EGG = registerItem(new Identifier(UAdd.MOD_ID, "piglin_brute_spawn_egg"), createSpawnEgg(EntityType.PIGLIN_BRUTE));
    public static final SpawnEgg PILLAGER_SPAWN_EGG = registerItem(new Identifier(UAdd.MOD_ID, "pillager_spawn_egg"), createSpawnEgg(EntityType.PILLAGER));
    public static final SpawnEgg POLAR_BEAR_SPAWN_EGG = registerItem(new Identifier(UAdd.MOD_ID, "polar_bear_spawn_egg"), createSpawnEgg(EntityType.POLAR_BEAR));
    public static final SpawnEgg PUFFERFISH_SPAWN_EGG = registerItem(new Identifier(UAdd.MOD_ID, "pufferfish_spawn_egg"), createSpawnEgg(EntityType.PUFFERFISH));
    public static final SpawnEgg RABBIT_SPAWN_EGG = registerItem(new Identifier(UAdd.MOD_ID, "rabbit_spawn_egg"), createSpawnEgg(EntityType.RABBIT));
    public static final SpawnEgg RAVAGER_SPAWN_EGG = registerItem(new Identifier(UAdd.MOD_ID, "ravager_spawn_egg"), createSpawnEgg(EntityType.RAVAGER));
    public static final SpawnEgg SALMON_SPAWN_EGG = registerItem(new Identifier(UAdd.MOD_ID, "salmon_spawn_egg"), createSpawnEgg(EntityType.SALMON));
    public static final SpawnEgg SHEEP_SPAWN_EGG = registerItem(new Identifier(UAdd.MOD_ID, "sheep_spawn_egg"), createSpawnEgg(EntityType.SHEEP));
    public static final SpawnEgg SHULKER_SPAWN_EGG = registerItem(new Identifier(UAdd.MOD_ID, "shulker_spawn_egg"), createSpawnEgg(EntityType.SHULKER));
    public static final SpawnEgg SILVERFISH_SPAWN_EGG = registerItem(new Identifier(UAdd.MOD_ID, "silverfish_spawn_egg"), createSpawnEgg(EntityType.SILVERFISH));
    public static final SpawnEgg SKELETON_SPAWN_EGG = registerItem(new Identifier(UAdd.MOD_ID, "skeleton_spawn_egg"), createSpawnEgg(EntityType.SKELETON));
    public static final SpawnEgg SLIME_SPAWN_EGG = registerItem(new Identifier(UAdd.MOD_ID, "slime_spawn_egg"), createSpawnEgg(EntityType.SLIME));
    public static final SpawnEgg SNOW_GOLEM_SPAWN_EGG = registerItem(new Identifier(UAdd.MOD_ID, "snow_golem_spawn_egg"), createSpawnEgg(EntityType.SNOW_GOLEM));
    public static final SpawnEgg SPIDER_SPAWN_EGG = registerItem(new Identifier(UAdd.MOD_ID, "spider_spawn_egg"), createSpawnEgg(EntityType.SPIDER));
    public static final SpawnEgg SQUID_SPAWN_EGG = registerItem(new Identifier(UAdd.MOD_ID, "squid_spawn_egg"), createSpawnEgg(EntityType.SQUID));
    public static final SpawnEgg STRAY_SPAWN_EGG = registerItem(new Identifier(UAdd.MOD_ID, "stray_spawn_egg"), createSpawnEgg(EntityType.STRAY));
    public static final SpawnEgg STRIDER_SPAWN_EGG = registerItem(new Identifier(UAdd.MOD_ID, "strider_spawn_egg"), createSpawnEgg(EntityType.STRIDER));
    public static final SpawnEgg TROPICAL_FISH_SPAWN_EGG = registerItem(new Identifier(UAdd.MOD_ID, "tropical_fish_spawn_egg"), createSpawnEgg(EntityType.TROPICAL_FISH));
    public static final SpawnEgg TURTLE_SPAWN_EGG = registerItem(new Identifier(UAdd.MOD_ID, "turtle_spawn_egg"), createSpawnEgg(EntityType.TURTLE));
    public static final SpawnEgg VEX_SPAWN_EGG = registerItem(new Identifier(UAdd.MOD_ID, "vex_spawn_egg"), createSpawnEgg(EntityType.VEX));
    public static final SpawnEgg VILLAGER_SPAWN_EGG = registerItem(new Identifier(UAdd.MOD_ID, "villager_spawn_egg"), createSpawnEgg(EntityType.VILLAGER));
    public static final SpawnEgg VINDICATOR_SPAWN_EGG = registerItem(new Identifier(UAdd.MOD_ID, "vindicator_spawn_egg"), createSpawnEgg(EntityType.VINDICATOR));
    public static final SpawnEgg WARDEN_SPAWN_EGG = registerItem(new Identifier(UAdd.MOD_ID, "warden_spawn_egg"), createSpawnEgg(EntityType.WARDEN));
    public static final SpawnEgg WITCH_SPAWN_EGG = registerItem(new Identifier(UAdd.MOD_ID, "witch_spawn_egg"), createSpawnEgg(EntityType.WITCH));
    public static final SpawnEgg WITHER_SKELETON_SPAWN_EGG = registerItem(new Identifier(UAdd.MOD_ID, "wither_skeleton_spawn_egg"), createSpawnEgg(EntityType.WITHER_SKELETON));
    public static final SpawnEgg WOLF_SPAWN_EGG = registerItem(new Identifier(UAdd.MOD_ID, "wolf_spawn_egg"), createSpawnEgg(EntityType.WOLF));
    public static final SpawnEgg ZOGLIN_SPAWN_EGG = registerItem(new Identifier(UAdd.MOD_ID, "zoglin_spawn_egg"), createSpawnEgg(EntityType.ZOGLIN));
    public static final SpawnEgg ZOMBIE_SPAWN_EGG = registerItem(new Identifier(UAdd.MOD_ID, "zombie_spawn_egg"), createSpawnEgg(EntityType.ZOMBIE));
    public static final SpawnEgg ZOMBIE_VILLAGER_SPAWN_EGG = registerItem(new Identifier(UAdd.MOD_ID, "zombie_villager_spawn_egg"), createSpawnEgg(EntityType.ZOMBIE_VILLAGER));
    public static final SpawnEgg ZOMBIFIED_PIGLIN_SPAWN_EGG = registerItem(new Identifier(UAdd.MOD_ID, "zombified_piglin_spawn_egg"), createSpawnEgg(EntityType.ZOMBIFIED_PIGLIN));
    //Materials
    // -- Misc
    public static final Item EMPTY_DISC = registerItem(new Identifier(UAdd.MOD_ID, "empty_disc"), createItem());
    public static final AliasedBlockItem PLANT_FIBRE = registerBlockItem(new Identifier(UAdd.MOD_ID, "plant_fibre"), new AliasedBlockItem(PLANT_FIBRE_TRIPWIRE, new FabricItemSettings()));
    public static final DamageableItem BUNDLED_FLOWERS = registerItem(new Identifier(UAdd.MOD_ID, "bundled_flowers"), new DamageableItem(new FabricItemSettings().maxCount(1).maxDamage(16)));
    public static final UItem CACTUS_LINING = registerItem(new Identifier(UAdd.MOD_ID, "cactus_lining"), new UItem(new FabricItemSettings(), SpecialEffects.CACTUS_LINING));
    public static final UItem OBSIDIAN_PADDING = registerItem(new Identifier(UAdd.MOD_ID, "obsidian_padding"), new UItem(new FabricItemSettings(), SpecialEffects.OBSIDIAN_PADDING));
    public static final Item DRAGON_SCALE = registerItem(new Identifier(UAdd.MOD_ID, "dragon_scale"), new Item(new FabricItemSettings().fireproof().rarity(Rarity.UNCOMMON)));
    public static final Item DRAGON_HEART = registerItem(new Identifier(UAdd.MOD_ID, "dragon_heart"), new Item(new FabricItemSettings().fireproof().rarity(Rarity.EPIC)));
    public static final Item WEATHERED_SCRAP = registerItem(new Identifier(UAdd.MOD_ID, "weathered_scrap"), new Item(new FabricItemSettings()));
    public static final Item ANCIENT_SHARD = registerItem(new Identifier(UAdd.MOD_ID, "ancient_shard"), new Item(new FabricItemSettings().fireproof()));
    public static final Item ENDER_PEARL_SHARD = registerItem(new Identifier(UAdd.MOD_ID, "ender_pearl_shard"), createItem());
    public static final MagicBook MAGIC_BOOK = registerItem(new Identifier(UAdd.MOD_ID, "magic_book"), new MagicBook(new FabricItemSettings().maxCount(1).maxDamage(4).rarity(Rarity.EPIC), Formatting.GRAY));
    public static final Item TREE_FELLING_UPGRADE = registerItem(new Identifier(UAdd.MOD_ID, "tree_felling_upgrade"), createItem());
    public static final Item IRON_BUNDLE_UPGRADE = registerItem(new Identifier(UAdd.MOD_ID, "iron_bundle_upgrade"), createItem());
    public static final Item DIAMOND_BUNDLE_UPGRADE = registerItem(new Identifier(UAdd.MOD_ID, "diamond_bundle_upgrade"), createItem());
    // -- Meshes
    public static final Mesh PLANT_MESH = registerItem(new Identifier(UAdd.MOD_ID, "plant_mesh"), new Mesh(MeshType.PLANT, new FabricItemSettings()));
    public static final Mesh STRING_MESH = registerItem(new Identifier(UAdd.MOD_ID, "string_mesh"), new Mesh(MeshType.STRING, new FabricItemSettings()));
    public static final Mesh FLINT_MESH = registerItem(new Identifier(UAdd.MOD_ID, "flint_mesh"), new Mesh(MeshType.FLINT, new FabricItemSettings()));
    public static final Mesh IRON_MESH = registerItem(new Identifier(UAdd.MOD_ID, "iron_mesh"), new Mesh(MeshType.IRON, new FabricItemSettings()));
    public static final Mesh GOLD_MESH = registerItem(new Identifier(UAdd.MOD_ID, "gold_mesh"), new Mesh(MeshType.GOLD, new FabricItemSettings()));
    public static final Mesh DIAMOND_MESH = registerItem(new Identifier(UAdd.MOD_ID, "diamond_mesh"), new Mesh(MeshType.DIAMOND, new FabricItemSettings()));
    public static final Mesh NETHERITE_MESH = registerItem(new Identifier(UAdd.MOD_ID, "netherite_mesh"), new Mesh(MeshType.NETHERITE, new FabricItemSettings().fireproof()));
    public static final Mesh DRAGON_MESH = registerItem(new Identifier(UAdd.MOD_ID, "dragon_mesh"), new Mesh(MeshType.DRAGON, new FabricItemSettings().fireproof()));
    // -- Dusts
    public static final Item DIRT_PILE = registerItem(new Identifier(UAdd.MOD_ID, "dirt_pile"), createItem());
    public static final Item SAND_PILE = registerItem(new Identifier(UAdd.MOD_ID, "sand_pile"), createItem());
    public static final Item RED_SAND_PILE = registerItem(new Identifier(UAdd.MOD_ID, "red_sand_pile"), createItem());
    public static final Item FLINT_SHARD = registerItem(new Identifier(UAdd.MOD_ID, "flint_shard"), createItem());
    public static final Item ROCK = registerItem(new Identifier(UAdd.MOD_ID, "rock"), createItem());
    public static final Item DEEPSLATE_ROCK = registerItem(new Identifier(UAdd.MOD_ID, "deepslate_rock"), createItem());
    public static final Item ASH = registerItem(new Identifier(UAdd.MOD_ID, "ash"), createItem());
    public static final Item EXOTIC_DUST = registerItem(new Identifier(UAdd.MOD_ID, "exotic_dust"), new Item(new FabricItemSettings().rarity(Rarity.UNCOMMON)));
    // -- Nuggets
    public static final Item RAW_COPPER_NUGGET = registerItem(new Identifier(UAdd.MOD_ID, "raw_copper_nugget"), createItem());
    public static final Item RAW_IRON_NUGGET = registerItem(new Identifier(UAdd.MOD_ID, "raw_iron_nugget"), createItem());
    public static final Item RAW_GOLD_NUGGET = registerItem(new Identifier(UAdd.MOD_ID, "raw_gold_nugget"), createItem());
    public static final Item COPPER_NUGGET = registerItem(new Identifier(UAdd.MOD_ID, "copper_nugget"), createItem());
    public static final Item EMERALD_NUGGET = registerItem(new Identifier(UAdd.MOD_ID, "emerald_nugget"), createItem());
    public static final Item DIAMOND_NUGGET = registerItem(new Identifier(UAdd.MOD_ID, "diamond_nugget"), createItem());
    public static final Item NETHERITE_NUGGET = registerItem(new Identifier(UAdd.MOD_ID, "netherite_nugget"), new Item(new FabricItemSettings().fireproof()));
    public static final Item FORTRESS_NUGGET = registerItem(new Identifier(UAdd.MOD_ID, "fortress_nugget"), createItem());
    // -- Ingots
    public static final Item RUBY = registerItem(new Identifier(UAdd.MOD_ID, "ruby"), createItem());
    public static final Item MAGIC_INGOT = registerItem(new Identifier(UAdd.MOD_ID, "magic_ingot"), createItem());
    public static final GlintItem ENCHANTED_MAGIC_INGOT = registerItem(new Identifier(UAdd.MOD_ID, "enchanted_magic_ingot"), new GlintItem(new FabricItemSettings().rarity(Rarity.RARE)));
    public static final Item BLAZE_METAL = registerItem(new Identifier(UAdd.MOD_ID, "blaze_metal"), createItem());
    public static final Item EXOTIC_INGOT = registerItem(new Identifier(UAdd.MOD_ID, "exotic_ingot"), new Item(new FabricItemSettings().rarity(Rarity.UNCOMMON)));
    // -- Tool Components
    public static final Item NETHERITE_STICK = registerItem(new Identifier(UAdd.MOD_ID, "netherite_stick"), new Item(new FabricItemSettings().fireproof()));
    //Hammer
    public static final HammerItem MAKESHIFT_HAMMER = registerItem(new Identifier(UAdd.MOD_ID, "makeshift_hammer"), new HammerItem(ToolMaterials.WOOD, 1, -3.2F, new FabricItemSettings()));
    public static final HammerItem HAMMER = registerItem(new Identifier(UAdd.MOD_ID, "hammer"), new HammerItem(ToolMaterials.IRON, 1, -3.2F, new FabricItemSettings()));
    public static final HammerItem AMETHYST_HAMMER = registerItem(new Identifier(UAdd.MOD_ID, "amethyst_hammer"), new HammerItem(UToolMaterials.AMETHYST, 1, -3.2F, new FabricItemSettings(), SpecialEffects.CRYSTALLIZED_XP));
    //Tools
    public static final ScytheItem WOODEN_SCYTHE = registerItem(new Identifier(UAdd.MOD_ID, "wooden_scythe"), new ScytheItem(ToolMaterials.WOOD, 4.5F, -2.8F, new FabricItemSettings()));
    public static final ScytheItem STONE_SCYTHE = registerItem(new Identifier(UAdd.MOD_ID, "stone_scythe"), new ScytheItem(ToolMaterials.STONE, 4.5F, -2.8F, new FabricItemSettings()));
    public static final ScytheItem IRON_SCYTHE = registerItem(new Identifier(UAdd.MOD_ID, "iron_scythe"), new ScytheItem(ToolMaterials.IRON, 4.5F, -2.8F, new FabricItemSettings()));
    public static final ScytheItem GOLDEN_SCYTHE = registerItem(new Identifier(UAdd.MOD_ID, "golden_scythe"), new ScytheItem(ToolMaterials.GOLD, 4.5F, -2.8F, new FabricItemSettings()));
    public static final ScytheItem DIAMOND_SCYTHE = registerItem(new Identifier(UAdd.MOD_ID, "diamond_scythe"), new ScytheItem(ToolMaterials.DIAMOND, 4.5F, -2.8F, new FabricItemSettings()));
    public static final ScytheItem NETHERITE_SCYTHE = registerItem(new Identifier(UAdd.MOD_ID, "netherite_scythe"), new ScytheItem(ToolMaterials.NETHERITE, 4.5F, -2.8F, new FabricItemSettings().fireproof()));
    public static final USwordItem AMETHYST_SWORD = registerItem(new Identifier(UAdd.MOD_ID, "amethyst_sword"), new USwordItem(UToolMaterials.AMETHYST, 3, -2.4F, new FabricItemSettings(), SpecialEffects.CRYSTALLIZED_XP));
    public static final UShovelItem AMETHYST_SHOVEL = registerItem(new Identifier(UAdd.MOD_ID, "amethyst_shovel"), new UShovelItem(UToolMaterials.AMETHYST, 1.5F, -3.0F, new FabricItemSettings(), SpecialEffects.CRYSTALLIZED_XP));
    public static final UPickaxeItem AMETHYST_PICKAXE = registerItem(new Identifier(UAdd.MOD_ID, "amethyst_pickaxe"), new UPickaxeItem(UToolMaterials.AMETHYST, 1, -2.8F, new FabricItemSettings(), SpecialEffects.CRYSTALLIZED_XP));
    public static final UAxeItem AMETHYST_AXE = registerItem(new Identifier(UAdd.MOD_ID, "amethyst_axe"), new UAxeItem(UToolMaterials.AMETHYST, 5.0F, -3F, new FabricItemSettings(), SpecialEffects.CRYSTALLIZED_XP));
    public static final UHoeItem AMETHYST_HOE = registerItem(new Identifier(UAdd.MOD_ID, "amethyst_hoe"), new UHoeItem(UToolMaterials.AMETHYST_P5, -2, 0.0F, new FabricItemSettings(), SpecialEffects.CRYSTALLIZED_XP));
    public static final ScytheItem AMETHYST_SCYTHE = registerItem(new Identifier(UAdd.MOD_ID, "amethyst_scythe"), new ScytheItem(UToolMaterials.AMETHYST, 4.5F, -2.8F, new FabricItemSettings(), SpecialEffects.CRYSTALLIZED_XP));
    public static final USwordItem EMERALD_SWORD = registerItem(new Identifier(UAdd.MOD_ID, "emerald_sword"), new USwordItem(UToolMaterials.EMERALD, 3, -2.4F, new FabricItemSettings()));
    public static final UShovelItem EMERALD_SHOVEL = registerItem(new Identifier(UAdd.MOD_ID, "emerald_shovel"), new UShovelItem(UToolMaterials.EMERALD, 1.5F, -3.0F, new FabricItemSettings()));
    public static final UPickaxeItem EMERALD_PICKAXE = registerItem(new Identifier(UAdd.MOD_ID, "emerald_pickaxe"), new UPickaxeItem(UToolMaterials.EMERALD, 1, -2.8F, new FabricItemSettings()));
    public static final UAxeItem EMERALD_AXE = registerItem(new Identifier(UAdd.MOD_ID, "emerald_axe"), new UAxeItem(UToolMaterials.EMERALD, 5.0F, -3.0F, new FabricItemSettings()));
    public static final UHoeItem EMERALD_HOE = registerItem(new Identifier(UAdd.MOD_ID, "emerald_hoe"), new UHoeItem(UToolMaterials.EMERALD, -3, 0.0F, new FabricItemSettings()));
    public static final ScytheItem EMERALD_SCYTHE = registerItem(new Identifier(UAdd.MOD_ID, "emerald_scythe"), new ScytheItem(UToolMaterials.EMERALD, 4.5F, -2.8F, new FabricItemSettings()));
    public static final USwordItem BLAZE_METAL_SWORD = registerItem(new Identifier(UAdd.MOD_ID, "blaze_metal_sword"), new USwordItem(UToolMaterials.BLAZE_METAL, 3, -2.4F, new FabricItemSettings(), SpecialEffects.AUTO_SMELT));
    public static final UShovelItem BLAZE_METAL_SHOVEL = registerItem(new Identifier(UAdd.MOD_ID, "blaze_metal_shovel"), new UShovelItem(UToolMaterials.BLAZE_METAL, 1.5F, -3.0F, new FabricItemSettings(), SpecialEffects.AUTO_SMELT));
    public static final UPickaxeItem BLAZE_METAL_PICKAXE = registerItem(new Identifier(UAdd.MOD_ID, "blaze_metal_pickaxe"), new UPickaxeItem(UToolMaterials.BLAZE_METAL, 1, -2.8F, new FabricItemSettings(), SpecialEffects.AUTO_SMELT));
    public static final UAxeItem BLAZE_METAL_AXE = registerItem(new Identifier(UAdd.MOD_ID, "blaze_metal_axe"), new UAxeItem(UToolMaterials.BLAZE_METAL, 5.0F, -3.0F, new FabricItemSettings(), SpecialEffects.AUTO_SMELT));
    public static final UHoeItem BLAZE_METAL_HOE = registerItem(new Identifier(UAdd.MOD_ID, "blaze_metal_hoe"), new UHoeItem(UToolMaterials.BLAZE_METAL_P5, -3, 0.0F, new FabricItemSettings(), SpecialEffects.AUTO_SMELT));
    public static final ScytheItem BLAZE_METAL_SCYTHE = registerItem(new Identifier(UAdd.MOD_ID, "blaze_metal_scythe"), new ScytheItem(UToolMaterials.BLAZE_METAL, 4.5F, -2.8F, new FabricItemSettings(), SpecialEffects.AUTO_SMELT));
    public static final USwordItem DRAGON_SCALE_SWORD = registerItem(new Identifier(UAdd.MOD_ID, "dragon_scale_sword"), new USwordItem(UToolMaterials.DRAGON_SCALE, 3, -2.4F, new FabricItemSettings().fireproof()));
    public static final UShovelItem DRAGON_SCALE_SHOVEL = registerItem(new Identifier(UAdd.MOD_ID, "dragon_scale_shovel"), new UShovelItem(UToolMaterials.DRAGON_SCALE, 1.5F, -3.0F, new FabricItemSettings().fireproof()));
    public static final UPickaxeItem DRAGON_SCALE_PICKAXE = registerItem(new Identifier(UAdd.MOD_ID, "dragon_scale_pickaxe"), new UPickaxeItem(UToolMaterials.DRAGON_SCALE, 1, -2.8F, new FabricItemSettings().fireproof()));
    public static final UAxeItem DRAGON_SCALE_AXE = registerItem(new Identifier(UAdd.MOD_ID, "dragon_scale_axe"), new UAxeItem(UToolMaterials.DRAGON_SCALE, 5.0F, -3.0F, new FabricItemSettings().fireproof()));
    public static final UHoeItem DRAGON_SCALE_HOE = registerItem(new Identifier(UAdd.MOD_ID, "dragon_scale_hoe"), new UHoeItem(UToolMaterials.DRAGON_SCALE, -4, 0.0F, new FabricItemSettings().fireproof()));
    public static final ScytheItem DRAGON_SCALE_SCYTHE = registerItem(new Identifier(UAdd.MOD_ID, "dragon_scale_scythe"), new ScytheItem(UToolMaterials.DRAGON_SCALE, 4.5F, -2.8F, new FabricItemSettings().fireproof()));
    //Armors
    public static final ArmorItem DRAGON_SCALE_HELMET = registerItem(new Identifier(UAdd.MOD_ID, "dragon_scale_helmet"), new ArmorItem(UArmorMaterials.DRAGON_SCALE, ArmorItem.Type.HELMET, new FabricItemSettings().fireproof()));
    public static final ArmorItem DRAGON_SCALE_CHESTPLATE = registerItem(new Identifier(UAdd.MOD_ID, "dragon_scale_chestplate"), new ArmorItem(UArmorMaterials.DRAGON_SCALE, ArmorItem.Type.CHESTPLATE, new FabricItemSettings().fireproof()));
    public static final ArmorItem DRAGON_SCALE_LEGGINGS = registerItem(new Identifier(UAdd.MOD_ID, "dragon_scale_leggings"), new ArmorItem(UArmorMaterials.DRAGON_SCALE, ArmorItem.Type.LEGGINGS, new FabricItemSettings().fireproof()));
    public static final ArmorItem DRAGON_SCALE_BOOTS = registerItem(new Identifier(UAdd.MOD_ID, "dragon_scale_boots"), new ArmorItem(UArmorMaterials.DRAGON_SCALE, ArmorItem.Type.BOOTS, new FabricItemSettings().fireproof()));
    //Utility
    public static final WarpPearl WARP_PEARL = registerItem(new Identifier(UAdd.MOD_ID, "warp_pearl"), new WarpPearl(new FabricItemSettings().maxCount(1).maxDamage(64)));
    public static final Bundle BUNDLE = registerItem(new Identifier(UAdd.MOD_ID, "bundle"), new Bundle(new FabricItemSettings().maxCount(1)));
    public static final IronBundle IRON_BUNDLE = registerItem(new Identifier(UAdd.MOD_ID, "iron_bundle"), new IronBundle(new FabricItemSettings().maxCount(1)));
    public static final DiamondBundle DIAMOND_BUNDLE = registerItem(new Identifier(UAdd.MOD_ID, "diamond_bundle"), new DiamondBundle(new FabricItemSettings().maxCount(1)));
    public static final NetheriteBundle NETHERITE_BUNDLE = registerItem(new Identifier(UAdd.MOD_ID, "netherite_bundle"), new NetheriteBundle(new FabricItemSettings().maxCount(1).fireproof()));
    public static final DragonBundle DRAGON_BUNDLE = registerItem(new Identifier(UAdd.MOD_ID, "dragon_bundle"), new DragonBundle(new FabricItemSettings().maxCount(1).fireproof().rarity(Rarity.EPIC)));
    public static final TraderSatchel TRADER_SATCHEL = registerItem(new Identifier(UAdd.MOD_ID, "trader_satchel"), new TraderSatchel(new FabricItemSettings().maxCount(1).rarity(Rarity.UNCOMMON)));
    //Food
    public static final AllayCookie ALLAY_COOKIE = registerItem(new Identifier(UAdd.MOD_ID, "allay_cookie"), new AllayCookie(new FabricItemSettings().food(UFoodComponents.ALLAY_COOKIE)));
    public static final StewItem BONE_STEW = registerItem(new Identifier(UAdd.MOD_ID, "bone_stew"), new StewItem(new FabricItemSettings().maxCount(1).food(UFoodComponents.BONE_STEW)));
    public static final Item BAT_WING = registerItem(new Identifier(UAdd.MOD_ID, "bat_wing"), new Item(new FabricItemSettings().food(UFoodComponents.BAT_WING)));
    public static final StewItem BAT_WING_STEW = registerItem(new Identifier(UAdd.MOD_ID, "bat_wing_stew"), new StewItem(new FabricItemSettings().maxCount(1).food(UFoodComponents.BAT_WING_STEW)));
    public static final Item FROG_LEG = registerItem(new Identifier(UAdd.MOD_ID, "frog_leg"), new Item(new FabricItemSettings().food(UFoodComponents.FROG_LEG)));
    public static final StewItem FROG_LEG_STEW = registerItem(new Identifier(UAdd.MOD_ID, "frog_leg_stew"), new StewItem(new FabricItemSettings().maxCount(1).food(UFoodComponents.FROG_LEG_STEW)));
    public static final Item DRAGON_FLESH = registerItem(new Identifier(UAdd.MOD_ID, "dragon_flesh"), new Item(new FabricItemSettings().food(UFoodComponents.DRAGON_FLESH).fireproof()));
    public static final StewItem DRACONIC_STEW = registerItem(new Identifier(UAdd.MOD_ID, "draconic_stew"), new StewItem(new FabricItemSettings().maxCount(1).food(UFoodComponents.DRACONIC_STEW)));
    public static final GlintItem MAGIC_APPLE = registerItem(new Identifier(UAdd.MOD_ID, "magic_apple"), new GlintItem(new FabricItemSettings().food(UFoodComponents.MAGIC_APPLE).rarity(Rarity.EPIC)));
    //Non-functional
    public static final Item MODIFIER = registerItem(new Identifier(UAdd.MOD_ID, "modifier"), createItem());
    private static Item createItem() {
        return new Item(new FabricItemSettings());
    }
    private static TooltipItem createTooltipItem() {
        return new TooltipItem(new FabricItemSettings(), Formatting.GRAY);
    }
    private static TooltipGlintItem createTooltipGlintItem() {
        return new TooltipGlintItem(new FabricItemSettings(), Formatting.GRAY);
    }
    private static SmithingTemplateItem createSmithingTemplate(String name) {
        List<Identifier> emptyBaseSlotTextures = List.of(
                new Identifier("item/empty_armor_slot_helmet"),
                new Identifier("item/empty_slot_sword"),
                new Identifier("item/empty_armor_slot_chestplate"),
                new Identifier("item/empty_slot_pickaxe"),
                new Identifier("item/empty_armor_slot_leggings"),
                new Identifier("item/empty_slot_axe"),
                new Identifier("item/empty_armor_slot_boots"),
                new Identifier("item/empty_slot_hoe"),
                new Identifier("item/empty_slot_shovel"));
        List<Identifier> emptyAdditionSlotTextures = List.of(
                new Identifier("item/empty_slot_ingot"));
        return new SmithingTemplateItem(
                Text.translatable("smithing_template.uselessadditions."+name+".applies_to").formatted(Formatting.BLUE),
                Text.translatable("smithing_template.uselessadditions."+name+".ingredients").formatted(Formatting.BLUE),
                Text.translatable("smithing_template.uselessadditions."+name).formatted(Formatting.GRAY),
                Text.translatable("smithing_template.uselessadditions."+name+".base_slot_description"),
                Text.translatable("smithing_template.uselessadditions."+name+".additions_slot_description"),
                emptyBaseSlotTextures,
                emptyAdditionSlotTextures);
    }
    private static SpawnEgg createSpawnEgg(EntityType<? extends MobEntity> type) {
        return new SpawnEgg(new FabricItemSettings(), type);
    }
    private static <T extends Item> T registerItem(Identifier id, T item) {
        return Registry.register(Registries.ITEM, id, item);
    }
    public static void itemTabs() {
        ItemGroupEvents.modifyEntriesEvent(UGroups.UAddTab).register(entries -> {
            // Mob Ore Shards
            entries.add(ALLAY_SHARD);
            entries.add(AXOLOTL_SHARD);
            entries.add(BAT_SHARD);
            entries.add(BEE_SHARD);
            entries.add(BLAZE_SHARD);
            entries.add(CAT_SHARD);
            entries.add(CAVE_SPIDER_SHARD);
            entries.add(CHICKEN_SHARD);
            entries.add(COD_SHARD);
            entries.add(COW_SHARD);
            entries.add(CREEPER_SHARD);
            entries.add(DOLPHIN_SHARD);
            entries.add(DONKEY_SHARD);
            entries.add(ENDERMAN_SHARD);
            entries.add(ENDERMITE_SHARD);
            entries.add(EVOKER_SHARD);
            entries.add(FOX_SHARD);
            entries.add(FROG_SHARD);
            entries.add(GHAST_SHARD);
            entries.add(GLOW_SQUID_SHARD);
            entries.add(GOAT_SHARD);
            entries.add(GUARDIAN_SHARD);
            entries.add(HOGLIN_SHARD);
            entries.add(HORSE_SHARD);
            entries.add(IRON_GOLEM_SHARD);
            entries.add(LLAMA_SHARD);
            entries.add(MAGMA_CUBE_SHARD);
            entries.add(OCELOT_SHARD);
            entries.add(PANDA_SHARD);
            entries.add(PARROT_SHARD);
            entries.add(PHANTOM_SHARD);
            entries.add(PIG_SHARD);
            entries.add(PIGLIN_SHARD);
            entries.add(PILLAGER_SHARD);
            entries.add(POLAR_BEAR_SHARD);
            entries.add(PUFFERFISH_SHARD);
            entries.add(RABBIT_SHARD);
            entries.add(RAVAGER_SHARD);
            entries.add(SALMON_SHARD);
            entries.add(SHEEP_SHARD);
            entries.add(SHULKER_SHARD);
            entries.add(SILVERFISH_SHARD);
            entries.add(SKELETON_SHARD);
            entries.add(SLIME_SHARD);
            entries.add(SNOW_GOLEM_SHARD);
            entries.add(SPIDER_SHARD);
            entries.add(SQUID_SHARD);
            entries.add(STRIDER_SHARD);
            entries.add(TROPICAL_FISH_SHARD);
            entries.add(TURTLE_SHARD);
            entries.add(VEX_SHARD);
            entries.add(VILLAGER_SHARD);
            entries.add(VINDICATOR_SHARD);
            entries.add(WARDEN_SHARD);
            entries.add(WITCH_SHARD);
            entries.add(WITHER_SKELETON_SHARD);
            entries.add(WOLF_SHARD);
            entries.add(ZOMBIE_SHARD);
            entries.add(SMALL_ALLAY_SHARD);
            entries.add(SMALL_AXOLOTL_SHARD);
            entries.add(SMALL_BAT_SHARD);
            entries.add(SMALL_BEE_SHARD);
            entries.add(SMALL_BLAZE_SHARD);
            entries.add(SMALL_CAT_SHARD);
            entries.add(SMALL_CAVE_SPIDER_SHARD);
            entries.add(SMALL_CHICKEN_SHARD);
            entries.add(SMALL_COD_SHARD);
            entries.add(SMALL_COW_SHARD);
            entries.add(SMALL_CREEPER_SHARD);
            entries.add(SMALL_DOLPHIN_SHARD);
            entries.add(SMALL_DONKEY_SHARD);
            entries.add(SMALL_ENDERMAN_SHARD);
            entries.add(SMALL_ENDERMITE_SHARD);
            entries.add(SMALL_EVOKER_SHARD);
            entries.add(SMALL_FOX_SHARD);
            entries.add(SMALL_FROG_SHARD);
            entries.add(SMALL_GHAST_SHARD);
            entries.add(SMALL_GLOW_SQUID_SHARD);
            entries.add(SMALL_GOAT_SHARD);
            entries.add(SMALL_GUARDIAN_SHARD);
            entries.add(SMALL_HOGLIN_SHARD);
            entries.add(SMALL_HORSE_SHARD);
            entries.add(SMALL_IRON_GOLEM_SHARD);
            entries.add(SMALL_LLAMA_SHARD);
            entries.add(SMALL_MAGMA_CUBE_SHARD);
            entries.add(SMALL_OCELOT_SHARD);
            entries.add(SMALL_PANDA_SHARD);
            entries.add(SMALL_PARROT_SHARD);
            entries.add(SMALL_PHANTOM_SHARD);
            entries.add(SMALL_PIG_SHARD);
            entries.add(SMALL_PIGLIN_SHARD);
            entries.add(SMALL_PILLAGER_SHARD);
            entries.add(SMALL_POLAR_BEAR_SHARD);
            entries.add(SMALL_PUFFERFISH_SHARD);
            entries.add(SMALL_RABBIT_SHARD);
            entries.add(SMALL_RAVAGER_SHARD);
            entries.add(SMALL_SALMON_SHARD);
            entries.add(SMALL_SHEEP_SHARD);
            entries.add(SMALL_SHULKER_SHARD);
            entries.add(SMALL_SILVERFISH_SHARD);
            entries.add(SMALL_SKELETON_SHARD);
            entries.add(SMALL_SLIME_SHARD);
            entries.add(SMALL_SNOW_GOLEM_SHARD);
            entries.add(SMALL_SPIDER_SHARD);
            entries.add(SMALL_SQUID_SHARD);
            entries.add(SMALL_STRIDER_SHARD);
            entries.add(SMALL_TROPICAL_FISH_SHARD);
            entries.add(SMALL_TURTLE_SHARD);
            entries.add(SMALL_VEX_SHARD);
            entries.add(SMALL_VILLAGER_SHARD);
            entries.add(SMALL_VINDICATOR_SHARD);
            entries.add(SMALL_WARDEN_SHARD);
            entries.add(SMALL_WITCH_SHARD);
            entries.add(SMALL_WITHER_SKELETON_SHARD);
            entries.add(SMALL_WOLF_SHARD);
            entries.add(SMALL_ZOMBIE_SHARD);
            // Spawn Eggs
            entries.add(ALLAY_SPAWN_EGG);
            entries.add(AXOLOTL_SPAWN_EGG);
            entries.add(BAT_SPAWN_EGG);
            entries.add(BEE_SPAWN_EGG);
            entries.add(BLAZE_SPAWN_EGG);
            entries.add(CAT_SPAWN_EGG);
            entries.add(CAVE_SPIDER_SPAWN_EGG);
            entries.add(CHICKEN_SPAWN_EGG);
            entries.add(COD_SPAWN_EGG);
            entries.add(COW_SPAWN_EGG);
            entries.add(CREEPER_SPAWN_EGG);
            entries.add(DOLPHIN_SPAWN_EGG);
            entries.add(DONKEY_SPAWN_EGG);
            entries.add(DROWNED_SPAWN_EGG);
            entries.add(ENDERMAN_SPAWN_EGG);
            entries.add(ENDERMITE_SPAWN_EGG);
            entries.add(ELDER_GUARDIAN_SPAWN_EGG);
            entries.add(EVOKER_SPAWN_EGG);
            entries.add(FOX_SPAWN_EGG);
            entries.add(FRIGID_ZOMBIE_SPAWN_EGG);
            entries.add(FROG_SPAWN_EGG);
            entries.add(GHAST_SPAWN_EGG);
            entries.add(GLOW_SQUID_SPAWN_EGG);
            entries.add(GOAT_SPAWN_EGG);
            entries.add(GUARDIAN_SPAWN_EGG);
            entries.add(HOGLIN_SPAWN_EGG);
            entries.add(HORSE_SPAWN_EGG);
            entries.add(HUSK_SPAWN_EGG);
            entries.add(IRON_GOLEM_SPAWN_EGG);
            entries.add(LLAMA_SPAWN_EGG);
            entries.add(MAGMA_CUBE_SPAWN_EGG);
            entries.add(OCELOT_SPAWN_EGG);
            entries.add(PANDA_SPAWN_EGG);
            entries.add(PARROT_SPAWN_EGG);
            entries.add(PHANTOM_SPAWN_EGG);
            entries.add(PIG_SPAWN_EGG);
            entries.add(PIGLIN_SPAWN_EGG);
            entries.add(PIGLIN_BRUTE_SPAWN_EGG);
            entries.add(PILLAGER_SPAWN_EGG);
            entries.add(POLAR_BEAR_SPAWN_EGG);
            entries.add(PUFFERFISH_SPAWN_EGG);
            entries.add(RABBIT_SPAWN_EGG);
            entries.add(RAVAGER_SPAWN_EGG);
            entries.add(SALMON_SPAWN_EGG);
            entries.add(SHEEP_SPAWN_EGG);
            entries.add(SHULKER_SPAWN_EGG);
            entries.add(SILVERFISH_SPAWN_EGG);
            entries.add(SKELETON_SPAWN_EGG);
            entries.add(SLIME_SPAWN_EGG);
            entries.add(SNOW_GOLEM_SPAWN_EGG);
            entries.add(SPIDER_SPAWN_EGG);
            entries.add(SQUID_SPAWN_EGG);
            entries.add(STRAY_SPAWN_EGG);
            entries.add(STRIDER_SPAWN_EGG);
            entries.add(TROPICAL_FISH_SPAWN_EGG);
            entries.add(TURTLE_SPAWN_EGG);
            entries.add(VEX_SPAWN_EGG);
            entries.add(VILLAGER_SPAWN_EGG);
            entries.add(VINDICATOR_SPAWN_EGG);
            entries.add(WARDEN_SPAWN_EGG);
            entries.add(WITCH_SPAWN_EGG);
            entries.add(WITHER_SKELETON_SPAWN_EGG);
            entries.add(WOLF_SPAWN_EGG);
            entries.add(ZOGLIN_SPAWN_EGG);
            entries.add(ZOMBIE_SPAWN_EGG);
            entries.add(ZOMBIE_VILLAGER_SPAWN_EGG);
            entries.add(ZOMBIFIED_PIGLIN_SPAWN_EGG);
            // Materials
            // -- Misc
            entries.add(EMPTY_DISC);
            entries.add(PLANT_FIBRE);
            entries.add(BUNDLED_FLOWERS);
            //
            entries.add(CACTUS_LINING);
            entries.add(OBSIDIAN_PADDING);
            //
            entries.add(DRAGON_SCALE);
            entries.add(DRAGON_HEART);
            entries.add(WEATHERED_SCRAP);
            entries.add(ANCIENT_SHARD);
            entries.add(ENDER_PEARL_SHARD);
            entries.add(MAGIC_BOOK);
            entries.add(TREE_FELLING_UPGRADE);
            entries.add(IRON_BUNDLE_UPGRADE);
            entries.add(DIAMOND_BUNDLE_UPGRADE);
            // -- Meshes
            entries.add(PLANT_MESH);
            entries.add(STRING_MESH);
            entries.add(FLINT_MESH);
            entries.add(IRON_MESH);
            entries.add(GOLD_MESH);
            entries.add(DIAMOND_MESH);
            entries.add(NETHERITE_MESH);
            entries.add(DRAGON_MESH);
            // -- Dusts
            entries.add(DIRT_PILE);
            entries.add(SAND_PILE);
            entries.add(RED_SAND_PILE);
            entries.add(FLINT_SHARD);
            entries.add(ROCK);
            entries.add(DEEPSLATE_ROCK);
            entries.add(ASH);
            entries.add(EXOTIC_DUST);
            // -- Nuggets
            entries.add(RAW_COPPER_NUGGET);
            entries.add(RAW_IRON_NUGGET);
            entries.add(RAW_GOLD_NUGGET);
            entries.add(COPPER_NUGGET);
            entries.add(EMERALD_NUGGET);
            entries.add(DIAMOND_NUGGET);
            entries.add(NETHERITE_NUGGET);
            entries.add(FORTRESS_NUGGET);
            // -- Ingots
            entries.add(RUBY);
            entries.add(MAGIC_INGOT);
            entries.add(ENCHANTED_MAGIC_INGOT);
            entries.add(BLAZE_METAL);
            entries.add(EXOTIC_INGOT);
            // -- Tool Components
            entries.add(NETHERITE_STICK);
            // Hammer
            entries.add(MAKESHIFT_HAMMER.getDefaultStack());
            entries.add(HAMMER.getDefaultStack());
            entries.add(AMETHYST_HAMMER.getDefaultStack());
            // Tools
            entries.add(WOODEN_SCYTHE.getDefaultStack());
            entries.add(STONE_SCYTHE.getDefaultStack());
            entries.add(IRON_SCYTHE.getDefaultStack());
            entries.add(GOLDEN_SCYTHE.getDefaultStack());
            entries.add(DIAMOND_SCYTHE.getDefaultStack());
            entries.add(NETHERITE_SCYTHE.getDefaultStack());
            entries.add(AMETHYST_SWORD.getDefaultStack());
            entries.add(AMETHYST_SHOVEL.getDefaultStack());
            entries.add(AMETHYST_PICKAXE.getDefaultStack());
            entries.add(AMETHYST_AXE.getDefaultStack());
            entries.add(AMETHYST_HOE.getDefaultStack());
            entries.add(AMETHYST_SCYTHE.getDefaultStack());
            entries.add(EMERALD_SWORD.getDefaultStack());
            entries.add(EMERALD_SHOVEL.getDefaultStack());
            entries.add(EMERALD_PICKAXE.getDefaultStack());
            entries.add(EMERALD_AXE.getDefaultStack());
            entries.add(EMERALD_HOE.getDefaultStack());
            entries.add(EMERALD_SCYTHE.getDefaultStack());
            entries.add(BLAZE_METAL_SWORD.getDefaultStack());
            entries.add(BLAZE_METAL_SHOVEL.getDefaultStack());
            entries.add(BLAZE_METAL_PICKAXE.getDefaultStack());
            entries.add(BLAZE_METAL_AXE.getDefaultStack());
            entries.add(BLAZE_METAL_HOE.getDefaultStack());
            entries.add(BLAZE_METAL_SCYTHE.getDefaultStack());
            entries.add(DRAGON_SCALE_SWORD.getDefaultStack());
            entries.add(DRAGON_SCALE_SHOVEL.getDefaultStack());
            entries.add(DRAGON_SCALE_PICKAXE.getDefaultStack());
            entries.add(DRAGON_SCALE_AXE.getDefaultStack());
            entries.add(DRAGON_SCALE_HOE.getDefaultStack());
            entries.add(DRAGON_SCALE_SCYTHE.getDefaultStack());
            // Armor
            entries.add(DRAGON_SCALE_HELMET.getDefaultStack());
            entries.add(DRAGON_SCALE_CHESTPLATE.getDefaultStack());
            entries.add(DRAGON_SCALE_LEGGINGS.getDefaultStack());
            entries.add(DRAGON_SCALE_BOOTS.getDefaultStack());
            // Utility
            entries.add(WARP_PEARL);
            entries.add(BUNDLE);
            entries.add(IRON_BUNDLE);
            entries.add(DIAMOND_BUNDLE);
            entries.add(NETHERITE_BUNDLE);
            entries.add(DRAGON_BUNDLE);
            entries.add(TRADER_SATCHEL);
            // Food
            entries.add(ALLAY_COOKIE);
            entries.add(BONE_STEW);
            entries.add(BAT_WING);
            entries.add(BAT_WING_STEW);
            entries.add(FROG_LEG);
            entries.add(FROG_LEG_STEW);
            entries.add(DRAGON_FLESH);
            entries.add(DRACONIC_STEW);
            entries.add(MAGIC_APPLE);
            // Misc
            entries.add(SIEVE.asItem());
            // Tables
            entries.add(ENHANCEMENT_TABLE.asItem());
            // Ores
            entries.add(ALLAY_ORE.asItem());
            entries.add(DEEPSLATE_ALLAY_ORE.asItem());
            entries.add(NETHER_ALLAY_ORE.asItem());
            entries.add(END_ALLAY_ORE.asItem());
            entries.add(AXOLOTL_ORE.asItem());
            entries.add(DEEPSLATE_AXOLOTL_ORE.asItem());
            entries.add(NETHER_AXOLOTL_ORE.asItem());
            entries.add(END_AXOLOTL_ORE.asItem());
            entries.add(BAT_ORE.asItem());
            entries.add(DEEPSLATE_BAT_ORE.asItem());
            entries.add(NETHER_BAT_ORE.asItem());
            entries.add(END_BAT_ORE.asItem());
            entries.add(BEE_ORE.asItem());
            entries.add(DEEPSLATE_BEE_ORE.asItem());
            entries.add(NETHER_BEE_ORE.asItem());
            entries.add(END_BEE_ORE.asItem());
            entries.add(BLAZE_ORE.asItem());
            entries.add(DEEPSLATE_BLAZE_ORE.asItem());
            entries.add(NETHER_BLAZE_ORE.asItem());
            entries.add(END_BLAZE_ORE.asItem());
            entries.add(CAT_ORE.asItem());
            entries.add(DEEPSLATE_CAT_ORE.asItem());
            entries.add(NETHER_CAT_ORE.asItem());
            entries.add(END_CAT_ORE.asItem());
            entries.add(CAVE_SPIDER_ORE.asItem());
            entries.add(DEEPSLATE_CAVE_SPIDER_ORE.asItem());
            entries.add(NETHER_CAVE_SPIDER_ORE.asItem());
            entries.add(END_CAVE_SPIDER_ORE.asItem());
            entries.add(CHICKEN_ORE.asItem());
            entries.add(DEEPSLATE_CHICKEN_ORE.asItem());
            entries.add(NETHER_CHICKEN_ORE.asItem());
            entries.add(END_CHICKEN_ORE.asItem());
            entries.add(COD_ORE.asItem());
            entries.add(DEEPSLATE_COD_ORE.asItem());
            entries.add(NETHER_COD_ORE.asItem());
            entries.add(END_COD_ORE.asItem());
            entries.add(COW_ORE.asItem());
            entries.add(DEEPSLATE_COW_ORE.asItem());
            entries.add(NETHER_COW_ORE.asItem());
            entries.add(END_COW_ORE.asItem());
            entries.add(CREEPER_ORE.asItem());
            entries.add(DEEPSLATE_CREEPER_ORE.asItem());
            entries.add(NETHER_CREEPER_ORE.asItem());
            entries.add(END_CREEPER_ORE.asItem());
            entries.add(DOLPHIN_ORE.asItem());
            entries.add(DEEPSLATE_DOLPHIN_ORE.asItem());
            entries.add(NETHER_DOLPHIN_ORE.asItem());
            entries.add(END_DOLPHIN_ORE.asItem());
            entries.add(DONKEY_ORE.asItem());
            entries.add(DEEPSLATE_DONKEY_ORE.asItem());
            entries.add(NETHER_DONKEY_ORE.asItem());
            entries.add(END_DONKEY_ORE.asItem());
            entries.add(ENDERMAN_ORE.asItem());
            entries.add(DEEPSLATE_ENDERMAN_ORE.asItem());
            entries.add(NETHER_ENDERMAN_ORE.asItem());
            entries.add(END_ENDERMAN_ORE.asItem());
            entries.add(ENDERMITE_ORE.asItem());
            entries.add(DEEPSLATE_ENDERMITE_ORE.asItem());
            entries.add(NETHER_ENDERMITE_ORE.asItem());
            entries.add(END_ENDERMITE_ORE.asItem());
            entries.add(EVOKER_ORE.asItem());
            entries.add(DEEPSLATE_EVOKER_ORE.asItem());
            entries.add(NETHER_EVOKER_ORE.asItem());
            entries.add(END_EVOKER_ORE.asItem());
            entries.add(FOX_ORE.asItem());
            entries.add(DEEPSLATE_FOX_ORE.asItem());
            entries.add(NETHER_FOX_ORE.asItem());
            entries.add(END_FOX_ORE.asItem());
            entries.add(FROG_ORE.asItem());
            entries.add(DEEPSLATE_FROG_ORE.asItem());
            entries.add(NETHER_FROG_ORE.asItem());
            entries.add(END_FROG_ORE.asItem());
            entries.add(GHAST_ORE.asItem());
            entries.add(DEEPSLATE_GHAST_ORE.asItem());
            entries.add(NETHER_GHAST_ORE.asItem());
            entries.add(END_GHAST_ORE.asItem());
            entries.add(GLOW_SQUID_ORE.asItem());
            entries.add(DEEPSLATE_GLOW_SQUID_ORE.asItem());
            entries.add(NETHER_GLOW_SQUID_ORE.asItem());
            entries.add(END_GLOW_SQUID_ORE.asItem());
            entries.add(GOAT_ORE.asItem());
            entries.add(DEEPSLATE_GOAT_ORE.asItem());
            entries.add(NETHER_GOAT_ORE.asItem());
            entries.add(END_GOAT_ORE.asItem());
            entries.add(GUARDIAN_ORE.asItem());
            entries.add(DEEPSLATE_GUARDIAN_ORE.asItem());
            entries.add(NETHER_GUARDIAN_ORE.asItem());
            entries.add(END_GUARDIAN_ORE.asItem());
            entries.add(HOGLIN_ORE.asItem());
            entries.add(DEEPSLATE_HOGLIN_ORE.asItem());
            entries.add(NETHER_HOGLIN_ORE.asItem());
            entries.add(END_HOGLIN_ORE.asItem());
            entries.add(HORSE_ORE.asItem());
            entries.add(DEEPSLATE_HORSE_ORE.asItem());
            entries.add(NETHER_HORSE_ORE.asItem());
            entries.add(END_HORSE_ORE.asItem());
            entries.add(IRON_GOLEM_ORE.asItem());
            entries.add(DEEPSLATE_IRON_GOLEM_ORE.asItem());
            entries.add(NETHER_IRON_GOLEM_ORE.asItem());
            entries.add(END_IRON_GOLEM_ORE.asItem());
            entries.add(LLAMA_ORE.asItem());
            entries.add(DEEPSLATE_LLAMA_ORE.asItem());
            entries.add(NETHER_LLAMA_ORE.asItem());
            entries.add(END_LLAMA_ORE.asItem());
            entries.add(MAGMA_CUBE_ORE.asItem());
            entries.add(DEEPSLATE_MAGMA_CUBE_ORE.asItem());
            entries.add(NETHER_MAGMA_CUBE_ORE.asItem());
            entries.add(END_MAGMA_CUBE_ORE.asItem());
            entries.add(OCELOT_ORE.asItem());
            entries.add(DEEPSLATE_OCELOT_ORE.asItem());
            entries.add(NETHER_OCELOT_ORE.asItem());
            entries.add(END_OCELOT_ORE.asItem());
            entries.add(PANDA_ORE.asItem());
            entries.add(DEEPSLATE_PANDA_ORE.asItem());
            entries.add(NETHER_PANDA_ORE.asItem());
            entries.add(END_PANDA_ORE.asItem());
            entries.add(PARROT_ORE.asItem());
            entries.add(DEEPSLATE_PARROT_ORE.asItem());
            entries.add(NETHER_PARROT_ORE.asItem());
            entries.add(END_PARROT_ORE.asItem());
            entries.add(PHANTOM_ORE.asItem());
            entries.add(DEEPSLATE_PHANTOM_ORE.asItem());
            entries.add(NETHER_PHANTOM_ORE.asItem());
            entries.add(END_PHANTOM_ORE.asItem());
            entries.add(PIG_ORE.asItem());
            entries.add(DEEPSLATE_PIG_ORE.asItem());
            entries.add(NETHER_PIG_ORE.asItem());
            entries.add(END_PIG_ORE.asItem());
            entries.add(PIGLIN_ORE.asItem());
            entries.add(DEEPSLATE_PIGLIN_ORE.asItem());
            entries.add(NETHER_PIGLIN_ORE.asItem());
            entries.add(END_PIGLIN_ORE.asItem());
            entries.add(PILLAGER_ORE.asItem());
            entries.add(DEEPSLATE_PILLAGER_ORE.asItem());
            entries.add(NETHER_PILLAGER_ORE.asItem());
            entries.add(END_PILLAGER_ORE.asItem());
            entries.add(POLAR_BEAR_ORE.asItem());
            entries.add(DEEPSLATE_POLAR_BEAR_ORE.asItem());
            entries.add(NETHER_POLAR_BEAR_ORE.asItem());
            entries.add(END_POLAR_BEAR_ORE.asItem());
            entries.add(PUFFERFISH_ORE.asItem());
            entries.add(DEEPSLATE_PUFFERFISH_ORE.asItem());
            entries.add(NETHER_PUFFERFISH_ORE.asItem());
            entries.add(END_PUFFERFISH_ORE.asItem());
            entries.add(RABBIT_ORE.asItem());
            entries.add(DEEPSLATE_RABBIT_ORE.asItem());
            entries.add(NETHER_RABBIT_ORE.asItem());
            entries.add(END_RABBIT_ORE.asItem());
            entries.add(RAVAGER_ORE.asItem());
            entries.add(DEEPSLATE_RAVAGER_ORE.asItem());
            entries.add(NETHER_RAVAGER_ORE.asItem());
            entries.add(END_RAVAGER_ORE.asItem());
            entries.add(SALMON_ORE.asItem());
            entries.add(DEEPSLATE_SALMON_ORE.asItem());
            entries.add(NETHER_SALMON_ORE.asItem());
            entries.add(END_SALMON_ORE.asItem());
            entries.add(SHEEP_ORE.asItem());
            entries.add(DEEPSLATE_SHEEP_ORE.asItem());
            entries.add(NETHER_SHEEP_ORE.asItem());
            entries.add(END_SHEEP_ORE.asItem());
            entries.add(SHULKER_ORE.asItem());
            entries.add(DEEPSLATE_SHULKER_ORE.asItem());
            entries.add(NETHER_SHULKER_ORE.asItem());
            entries.add(END_SHULKER_ORE.asItem());
            entries.add(SILVERFISH_ORE.asItem());
            entries.add(DEEPSLATE_SILVERFISH_ORE.asItem());
            entries.add(NETHER_SILVERFISH_ORE.asItem());
            entries.add(END_SILVERFISH_ORE.asItem());
            entries.add(SKELETON_ORE.asItem());
            entries.add(DEEPSLATE_SKELETON_ORE.asItem());
            entries.add(NETHER_SKELETON_ORE.asItem());
            entries.add(END_SKELETON_ORE.asItem());
            entries.add(SLIME_ORE.asItem());
            entries.add(DEEPSLATE_SLIME_ORE.asItem());
            entries.add(NETHER_SLIME_ORE.asItem());
            entries.add(END_SLIME_ORE.asItem());
            entries.add(SNOW_GOLEM_ORE.asItem());
            entries.add(DEEPSLATE_SNOW_GOLEM_ORE.asItem());
            entries.add(NETHER_SNOW_GOLEM_ORE.asItem());
            entries.add(END_SNOW_GOLEM_ORE.asItem());
            entries.add(SPIDER_ORE.asItem());
            entries.add(DEEPSLATE_SPIDER_ORE.asItem());
            entries.add(NETHER_SPIDER_ORE.asItem());
            entries.add(END_SPIDER_ORE.asItem());
            entries.add(SQUID_ORE.asItem());
            entries.add(DEEPSLATE_SQUID_ORE.asItem());
            entries.add(NETHER_SQUID_ORE.asItem());
            entries.add(END_SQUID_ORE.asItem());
            entries.add(STRIDER_ORE.asItem());
            entries.add(DEEPSLATE_STRIDER_ORE.asItem());
            entries.add(NETHER_STRIDER_ORE.asItem());
            entries.add(END_STRIDER_ORE.asItem());
            entries.add(TROPICAL_FISH_ORE.asItem());
            entries.add(DEEPSLATE_TROPICAL_FISH_ORE.asItem());
            entries.add(NETHER_TROPICAL_FISH_ORE.asItem());
            entries.add(END_TROPICAL_FISH_ORE.asItem());
            entries.add(TURTLE_ORE.asItem());
            entries.add(DEEPSLATE_TURTLE_ORE.asItem());
            entries.add(NETHER_TURTLE_ORE.asItem());
            entries.add(END_TURTLE_ORE.asItem());
            entries.add(VEX_ORE.asItem());
            entries.add(DEEPSLATE_VEX_ORE.asItem());
            entries.add(NETHER_VEX_ORE.asItem());
            entries.add(END_VEX_ORE.asItem());
            entries.add(VILLAGER_ORE.asItem());
            entries.add(DEEPSLATE_VILLAGER_ORE.asItem());
            entries.add(NETHER_VILLAGER_ORE.asItem());
            entries.add(END_VILLAGER_ORE.asItem());
            entries.add(VINDICATOR_ORE.asItem());
            entries.add(DEEPSLATE_VINDICATOR_ORE.asItem());
            entries.add(NETHER_VINDICATOR_ORE.asItem());
            entries.add(END_VINDICATOR_ORE.asItem());
            entries.add(WARDEN_ORE.asItem());
            entries.add(DEEPSLATE_WARDEN_ORE.asItem());
            entries.add(NETHER_WARDEN_ORE.asItem());
            entries.add(END_WARDEN_ORE.asItem());
            entries.add(WITCH_ORE.asItem());
            entries.add(DEEPSLATE_WITCH_ORE.asItem());
            entries.add(NETHER_WITCH_ORE.asItem());
            entries.add(END_WITCH_ORE.asItem());
            entries.add(WITHER_SKELETON_ORE.asItem());
            entries.add(DEEPSLATE_WITHER_SKELETON_ORE.asItem());
            entries.add(NETHER_WITHER_SKELETON_ORE.asItem());
            entries.add(END_WITHER_SKELETON_ORE.asItem());
            entries.add(WOLF_ORE.asItem());
            entries.add(DEEPSLATE_WOLF_ORE.asItem());
            entries.add(NETHER_WOLF_ORE.asItem());
            entries.add(END_WOLF_ORE.asItem());
            entries.add(ZOMBIE_ORE.asItem());
            entries.add(DEEPSLATE_ZOMBIE_ORE.asItem());
            entries.add(NETHER_ZOMBIE_ORE.asItem());
            entries.add(END_ZOMBIE_ORE.asItem());
        });
        ItemGroupEvents.modifyEntriesEvent(UGroups.SpawnersTab).register(entries -> {
            entries.add(EMPTY_SPAWNER.asItem());
            for (EntityType<?> entity : Registries.ENTITY_TYPE.stream().toList()) {
                if (entity == EntityType.PLAYER) continue;
                ItemStack spawner = new ItemStack(SURVIVAL_SPAWNER.asItem());
                spawner.getOrCreateNbt().putString("EntityStored",Registries.ENTITY_TYPE.getId(entity).toString());
                entries.add(spawner);
            }
        });
        ItemGroupEvents.modifyEntriesEvent(ItemGroups.SPAWN_EGGS).register(entries -> {
            entries.addBefore(Items.FROG_SPAWN_EGG, V_FRIGID_ZOMBIE_SPAWN_EGG);
        });
    }
}